site_name: TesseraeOnto
site_url: https://tsrproject.github.io/TSROnto/


nav:
    - Home: index.md
    - Info: info.md
    - Glossary: gloss.md
    - Bibliography: biblio.md

site_author: Giusy Grieco
site_description: documentation for ontologies on co-design practices research


repo_name: TSROnto
repo_url: https://github.com/TSRProject/TSROnto/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.footer
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: amber
      accent: deep purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: amber
      accent: deep purple

  markdown_extensions:
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - pymdownx.superfences

language: en




extra:
  version:
    provider: mike



